# Makefile for susieR package
.PHONY: all install document test test-coverage pkgdown lint style clean deep-clean check check-cran

# Default target
all: document install

## Install the package
install: document
	@echo "Installing package..."
	@Rscript -e "devtools::install('.', quiet = TRUE, upgrade = FALSE, build = FALSE)"

## Document the package (properly handling Rcpp compilation)
document:
	@echo "Ensuring DESCRIPTION has final newline..."
	@Rscript -e "lines <- readLines('DESCRIPTION'); writeLines(lines, 'DESCRIPTION')"
	@echo "Creating minimal NAMESPACE if missing..."
	@test -f NAMESPACE || ( echo "# Generated by roxygen2: do not edit by hand" > NAMESPACE && \
		echo "" >> NAMESPACE ) 
	@echo "Regenerating Rcpp exports..."
	@Rscript -e "Rcpp::compileAttributes('.')"
	@echo "Compiling shared library..."
	@Rscript -e "pkgbuild::compile_dll('.')"
	@echo "Documenting with roxygen2..."
	@Rscript -e "roxygen2::roxygenise('.', clean = TRUE)"

## Run tests
test:
	@echo "Running tests..."
	@Rscript -e "devtools::test('.')"

## Test with coverage
test-coverage:
	@echo "Running tests with coverage..."
	@Rscript -e "covr::package_coverage('.')"

## Build pkgdown site
pkgdown: document
	@echo "Building pkgdown site..."
	@Rscript -e "pkgdown::build_site('.', lazy = TRUE)"

## Run lintr
lint:
	@echo "Running lintr..."
	@Rscript -e "lintr::lint_package('.')"

## Format code with styler
style:
	@echo "Styling code..."
	@Rscript -e "styler::style_pkg('.')"

## Basic check
check: document
	@echo "Running basic checks..."
	@Rscript -e "devtools::check('.', document = FALSE)"

## Run CRAN check
check-cran: document
	@echo "Running CRAN checks..."
	@Rscript -e "devtools::check('.', cran = TRUE, document = FALSE)"

## Clean generated files (KEEP NAMESPACE to avoid issues)
clean:
	@echo "Cleaning generated files..."
	@rm -f src/*.o src/*.so src/*.dll
	@rm -f src/RcppExports.cpp R/RcppExports.R
	@rm -rf man
	@rm -f src/symbols.rds
	@rm -rf *.tar.gz *.Rcheck
	@echo "Clean complete (NAMESPACE preserved)"

## Deep clean (removes everything including NAMESPACE)
deep-clean:
	@echo "Deep cleaning all generated files..."
	@rm -f src/*.o src/*.so src/*.dll
	@rm -f src/RcppExports.cpp R/RcppExports.R
	@rm -rf man
	@rm -f NAMESPACE
	@rm -f src/symbols.rds
	@rm -rf *.tar.gz *.Rcheck
	@rm -rf .Rhistory .RData .Rproj.user
	@rm -rf docs
	@rm -rf inst/doc vignettes/*.html vignettes/*.R
	@echo "Deep clean complete"

## Quick development workflow (when NAMESPACE exists)
quick: 
	@echo "Quick rebuild (assumes NAMESPACE exists)..."
	@Rscript -e "Rcpp::compileAttributes('.')"
	@Rscript -e "devtools::install('.', quick = TRUE, upgrade = FALSE)"

## Load package for interactive use
load:
	@echo "Loading package..."
	@Rscript -e "devtools::load_all('.')"

## Help
help:
	@echo "susieR Makefile"
	@echo ""
	@echo "Main targets:"
	@echo "  make              - Document and install (default)"
	@echo "  make document     - Generate documentation (creates NAMESPACE if needed)"
	@echo "  make install      - Install package"
	@echo "  make test         - Run tests"
	@echo "  make test-coverage - Test coverage report"
	@echo "  make pkgdown      - Build pkgdown site"
	@echo "  make lint         - Run lintr"
	@echo "  make style        - Format code with styler"
	@echo "  make check        - Run R CMD check"
	@echo "  make check-cran   - Run CRAN check"
	@echo ""
	@echo "Maintenance:"
	@echo "  make clean        - Remove generated files (keeps NAMESPACE)"
	@echo "  make deep-clean   - Remove ALL generated files"
	@echo ""
	@echo "Quick targets:"
	@echo "  make quick        - Quick rebuild (when NAMESPACE exists)"
	@echo "  make load         - Load package for interactive use"
