---
title: "susie-gsea-0811"
author: "Kaiqian Zhang"
date: "8/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Matrix)
library(ggplot2)
library(microbenchmark)
library(profvis)
```

## Data

We use a specific gene set generated from `susie-gsea-0806` and investigate the speed of sparse version SuSiE on this GSEA data set.

```{r}
ygsea.sun = readRDS('sun_ygsea.rds')
Xgsea.sun = readRDS('sun_Xgsea.rds')
```

```{r}
Xgsea.sun.sparse = Xgsea.sun
Xgsea.sun.dense = as.matrix(Xgsea.sun)
```

## Use `profvis` to evaluate computational time line by line
```{r}
profvis({
  susie.dense.fit = susie(Xgsea.sun.dense,ygsea.sun)
})
```

```{r}
profvis({
  susie.sparse.fit = susie(Xgsea.sun.sparse,ygsea.sun)
})
```

## Microbenchmark visualization
```{r, warning=FALSE}
sparse.dense.test = microbenchmark(
  susie.sparse = susie(Xgsea.sun.sparse,ygsea.sun),
  susie.dense = susie(Xgsea.sun.dense,ygsea.sun),
  times=5
)
autoplot(sparse.dense.test)
```


