---
title: "Sparse matrix multiplication strategy"
author: "Kaiqian Zhang"
header-includes:
   - \usepackage{amsmath}
date: "9/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Goal
Our intention is to utilize sparse matrix multiplication to help reduce computation time. 

## General strategy
Given a large sparse matrix `X`, we want to compute some matrix multiplications associated with a scaled $\widetilde{X}$. We notice that after scaling, `X` becomes a dense matrix and is not possible for a sparse matrix multiplication. So we construct formulae to apply sparse matrix multiplication first on a standardized `X` since standardization does not affect its sparsity. Then we perform centering to get the same result.  

## Types of matrix multiplications
There are two types of matrix multiplications we want to investigate:

* Compute $\boldsymbol{\widetilde{X}b}$, where $\boldsymbol{\widetilde{X}}$ is an n by p scaled matrix and $\boldsymbol{b}$ is a p vector.

* Compute $\boldsymbol{\widetilde{X}^Ty}$, where $\boldsymbol{\widetilde{X}}$ is an n by p scaled matrix and $\boldsymbol{y}$ is an n vector.

## Results

This strategy has a decent performance when computing both $\boldsymbol{\widetilde{X}b}$ and $\boldsymbol{\widetilde{X}^Ty}$, compared to simple matrix multiplication `%*%`. Please see vignette `A minimal benchmark on sparse strategy` for details. 

## Strategy formulae details

### $\boldsymbol{\widetilde{X}b}$
Suppose we want to compute $\boldsymbol{\widetilde{X}b}$, where $\boldsymbol{\widetilde{X}}$ is a scaled n by p matrix and $\boldsymbol{b}$ is a p vector. Our goal is to express $\boldsymbol{\widetilde{X}b}$ into a term involving unscaled $\boldsymbol{X}$ matrix multiplication to achieve sparse matrix operation.

\begin{equation}
\begin{aligned}
\boldsymbol{\widetilde{X}b}
&= \sum_{j=1}^{p} \widetilde{X_{.j}}b_j \\
&= \sum_{j=1}^{p} \frac{X_{.j}-\mu_j}{\sigma_j}b_j \\
&= \sum_{j=1}^{p}\frac{X_{.j}}{\sigma_j}b_j - \sum_{j=1}^{p} \frac{\mu_j}{\sigma_j}b_j \\
&= \boldsymbol{X} \cdot \frac{\boldsymbol{b}}{\boldsymbol{\sigma}} -  \frac{\boldsymbol{\mu}}{\boldsymbol{\sigma}}\cdot \boldsymbol{b},
\end{aligned}
\end{equation}

where $\boldsymbol{\mu}$ is a p vector of column means and $\boldsymbol{\sigma}$ is a p vector of column standard deviations. 

### $\boldsymbol{\widetilde{X}^Ty}$
Suppose we want to compute $\boldsymbol{\widetilde{X}^Ty}$, where $\boldsymbol{\widetilde{X}}$ is a scaled n by p matrix and $\boldsymbol{y}$ is an n vector. Similarly, we express $\boldsymbol{\widetilde{X}^Ty}$ using unscaled $\boldsymbol{X}$ so that we can perform sparse matrix multiplication. We have the following:

\begin{equation}
\begin{aligned}
\boldsymbol{\widetilde{X}^Ty}
&= \sum_{i=1}^{n} \widetilde{X_{i.}}y_i \\
&= \sum_{i=1}^{n} \frac{X_{i.} - \boldsymbol{\mu}}{\boldsymbol{\sigma}}y_i \\
&= \frac{1}{\boldsymbol{\sigma}}\sum_{i=1}^{n}X_{i.}y_i - \frac{\boldsymbol{\mu}}{\boldsymbol{\sigma}}\sum_{i=1}^{n} y_i \\
&= \frac{1}{\boldsymbol{\sigma}}(\boldsymbol{X^Ty}) - \boldsymbol{\frac{\mu}{\sigma}y^T 1},
\end{aligned}
\end{equation}

where $\boldsymbol{\mu}$ is a p vector of column means and $\boldsymbol{\sigma}$ is a p vector of column standard deviations.



