---
title: "Trend filtering"
author: "Matthew Stephens"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Trend filtering demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE,comment = "#",fig.width = 4.5,
                      fig.height = 3,fig.align = "center",
                      fig.cap = "&nbsp;",dpi = 120)
```

This is an example of using susie to do trend filtering.

```{r}
library(susieR)
set.seed(1)
n=1000
delta = matrix(1,nrow=n,ncol=n)
for(i in 1:(n-1)){
  for(j in (i+1):n){
    delta[i,j] = -1
  }
}
delta = delta[,-1] # remove intercept as included by default
beta = c(rep(0,100),rep(1,100),rep(3,100),rep(-2,100),rep(0,600))
y = beta + rnorm(n)
s = susie(delta,y,L=10)
```

Plot results: the truth is green, and susie estimate is red.

```{r}
plot(y,pch = 20)
lines(predict(s),col=2,lwd=3)
lines(beta,col=3,lwd=3)
s$sigma2
```

Try something harder where the beta increases linearly:

```{r}
set.seed(1)
beta = seq(0,2,length=1000)
y = beta + rnorm(n)
s = susie(delta,y,L=10)
plot(y,pch = 20)
lines(predict(s),col=2,lwd=3)
lines(beta,col=3,lwd=3)
```

Compare with the lasso based solution. (This will require installation
of the genlasso package.)

```{r, eval=FALSE}
library(genlasso)
y.tf = trendfilter(y,ord=0)
y.tf.cv = cv.trendfilter(y.tf)
plot(y)
lines(predict(s),col=2,lwd=3)
lines(beta,col=3,lwd=3)
lines(y.tf$fit[,which(y.tf$lambda==y.tf.cv$lambda.min)],col=4,lwd=3)
```

What happens if we have trend plus sudden change.

```{r, eval=FALSE}
beta = beta + c(rep(0,500),rep(2,500))
y = beta + rnorm(n)
s = susie(delta,y,L=10)
plot(y)
lines(predict(s),col=2,lwd=3)
lines(beta,col=3,lwd=3)
y.tf = trendfilter(y,ord=0)
y.tf.cv = cv.trendfilter(y.tf)
lines(y.tf$fit[,which(y.tf$lambda==y.tf.cv$lambda.min)],col=4,lwd=3)
```
