MACOSX_DEPLOYMENT_TARGET:
  - '11.0'
c_stdlib_version:
  - if: linux
    then: 2.17
  - if: osx
    then: 11.0
c_stdlib:
  - if: linux
    then: sysroot
  - if: osx
    then: macosx_deployment_target
r_base:
  - 4.4
