// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// caisa_rcpp
Rcpp::List caisa_rcpp(const arma::mat& X, const arma::vec& y, const arma::vec& w, const arma::vec& sa2, arma::vec& pi, arma::vec& beta, arma::vec& r, double sigma2, const arma::uvec& o, int maxiter, int miniter, double convtol, double epstol, std::string method_q, bool updatepi, bool updatesigma, bool verbose);
RcppExport SEXP _susieR_caisa_rcpp(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP, SEXP sa2SEXP, SEXP piSEXP, SEXP betaSEXP, SEXP rSEXP, SEXP sigma2SEXP, SEXP oSEXP, SEXP maxiterSEXP, SEXP miniterSEXP, SEXP convtolSEXP, SEXP epstolSEXP, SEXP method_qSEXP, SEXP updatepiSEXP, SEXP updatesigmaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sa2(sa2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type o(oSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type miniter(miniterSEXP);
    Rcpp::traits::input_parameter< double >::type convtol(convtolSEXP);
    Rcpp::traits::input_parameter< double >::type epstol(epstolSEXP);
    Rcpp::traits::input_parameter< std::string >::type method_q(method_qSEXP);
    Rcpp::traits::input_parameter< bool >::type updatepi(updatepiSEXP);
    Rcpp::traits::input_parameter< bool >::type updatesigma(updatesigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(caisa_rcpp(X, y, w, sa2, pi, beta, r, sigma2, o, maxiter, miniter, convtol, epstol, method_q, updatepi, updatesigma, verbose));
    return rcpp_result_gen;
END_RCPP
}
// random_order
arma::uvec random_order(int p, int numiter);
RcppExport SEXP _susieR_random_order(SEXP pSEXP, SEXP numiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type numiter(numiterSEXP);
    rcpp_result_gen = Rcpp::wrap(random_order(p, numiter));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_mr_ash_rss
List rcpp_mr_ash_rss(const NumericVector& bhat, const NumericVector& shat, const NumericVector& z, const NumericMatrix& R, double var_y, int n, double sigma2_e, const NumericVector& s0, const NumericVector& w0, const NumericVector& mu1_init, double tol, int max_iter, bool update_w0, bool update_sigma, bool compute_ELBO, bool standardize, int ncpus);
RcppExport SEXP _susieR_rcpp_mr_ash_rss(SEXP bhatSEXP, SEXP shatSEXP, SEXP zSEXP, SEXP RSEXP, SEXP var_ySEXP, SEXP nSEXP, SEXP sigma2_eSEXP, SEXP s0SEXP, SEXP w0SEXP, SEXP mu1_initSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP update_w0SEXP, SEXP update_sigmaSEXP, SEXP compute_ELBOSEXP, SEXP standardizeSEXP, SEXP ncpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type bhat(bhatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type shat(shatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type var_y(var_ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_e(sigma2_eSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type s0(s0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu1_init(mu1_initSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type update_w0(update_w0SEXP);
    Rcpp::traits::input_parameter< bool >::type update_sigma(update_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_ELBO(compute_ELBOSEXP);
    Rcpp::traits::input_parameter< bool >::type standardize(standardizeSEXP);
    Rcpp::traits::input_parameter< int >::type ncpus(ncpusSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mr_ash_rss(bhat, shat, z, R, var_y, n, sigma2_e, s0, w0, mu1_init, tol, max_iter, update_w0, update_sigma, compute_ELBO, standardize, ncpus));
    return rcpp_result_gen;
END_RCPP
}
// compute_eloglik_from_eigen
double compute_eloglik_from_eigen(const arma::vec& eigenvalues, const arma::mat& eigenvectors, const arma::vec& z, const arma::vec& zbar, const arma::vec& diag_postb2, const arma::mat& Z, double sigma2, double lambda, double z_null_norm2);
RcppExport SEXP _susieR_compute_eloglik_from_eigen(SEXP eigenvaluesSEXP, SEXP eigenvectorsSEXP, SEXP zSEXP, SEXP zbarSEXP, SEXP diag_postb2SEXP, SEXP ZSEXP, SEXP sigma2SEXP, SEXP lambdaSEXP, SEXP z_null_norm2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type eigenvalues(eigenvaluesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eigenvectors(eigenvectorsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type zbar(zbarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type diag_postb2(diag_postb2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type z_null_norm2(z_null_norm2SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_eloglik_from_eigen(eigenvalues, eigenvectors, z, zbar, diag_postb2, Z, sigma2, lambda, z_null_norm2));
    return rcpp_result_gen;
END_RCPP
}
// compute_null_loglik
double compute_null_loglik(const arma::vec& eigenvalues, const arma::vec& Vtz, double sigma2, double lambda, double z_null_norm2);
RcppExport SEXP _susieR_compute_null_loglik(SEXP eigenvaluesSEXP, SEXP VtzSEXP, SEXP sigma2SEXP, SEXP lambdaSEXP, SEXP z_null_norm2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type eigenvalues(eigenvaluesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Vtz(VtzSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type z_null_norm2(z_null_norm2SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_null_loglik(eigenvalues, Vtz, sigma2, lambda, z_null_norm2));
    return rcpp_result_gen;
END_RCPP
}
// eigen_R_omega
Rcpp::List eigen_R_omega(const Rcpp::List& panel_R_list, const arma::vec& omega, int K, int p);
RcppExport SEXP _susieR_eigen_R_omega(SEXP panel_R_listSEXP, SEXP omegaSEXP, SEXP KSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type panel_R_list(panel_R_listSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_R_omega(panel_R_list, omega, K, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_susieR_caisa_rcpp", (DL_FUNC) &_susieR_caisa_rcpp, 17},
    {"_susieR_random_order", (DL_FUNC) &_susieR_random_order, 2},
    {"_susieR_rcpp_mr_ash_rss", (DL_FUNC) &_susieR_rcpp_mr_ash_rss, 17},
    {"_susieR_compute_eloglik_from_eigen", (DL_FUNC) &_susieR_compute_eloglik_from_eigen, 9},
    {"_susieR_compute_null_loglik", (DL_FUNC) &_susieR_compute_null_loglik, 5},
    {"_susieR_eigen_R_omega", (DL_FUNC) &_susieR_eigen_R_omega, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_susieR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
