<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fine-mapping examples • susieR</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Fine-mapping examples">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">susieR</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.1.13</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li>
  <a href="../articles/index.html">Vignettes</a>
</li>
<li>
  <a href="../reference/index.html">Functions</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/stephenslab/susieR">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Fine-mapping examples</h1>
                        <h4 class="author">Gao Wang</h4>
            
            <h4 class="date">June 26, 2018</h4>
      
      
      <div class="hidden name"><code>finemapping.Rmd</code></div>

    </div>

    
    
<p>This vignettes demonstrates <code>susieR</code> in the context of genetic fine-mapping. We use simulated data of expression level of a gene (<span class="math inline">\(y\)</span>) in <span class="math inline">\(N \approx 600\)</span> individuals. We want to identify with the genotype matrix <span class="math inline">\(X_{N\times P}\)</span> (<span class="math inline">\(P=1000\)</span>) the genetic variables that causes changes in expression level.</p>
<p>The simulated data-set is <a href="https://github.com/stephenslab/susieR/blob/master/inst/data/N3finemapping.rds">available here</a>, as part of the <code>susieR</code> package. It is simulated to have exactly 3 non-zero effects.</p>
<div id="the-data-set" class="section level2">
<h2 class="hasAnchor">
<a href="#the-data-set" class="anchor"></a>The data-set</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1">dat =<span class="st"> </span><span class="kw">readRDS</span>(<span class="kw">system.file</span>(<span class="st">"data"</span>, <span class="st">"N3finemapping.rds"</span>, <span class="dt">package =</span> <span class="st">"susieR"</span>))</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">names</span>(dat)</a></code></pre></div>
<pre><code>## [1] "data"     "sumstats"</code></pre>
<p><code>data</code> contains regression data-set <span class="math inline">\(X\)</span> and <span class="math inline">\(y\)</span>, along with some other relevant properties in the context of genetic studies. It also contains the “true” regression coefficent the data is simulated from.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">names</span>(dat<span class="op">$</span>data)</a></code></pre></div>
<pre><code>## [1] "X"                 "chrom"             "pos"              
## [4] "true_coef"         "residual_variance" "Y"                
## [7] "allele_freq"       "V"</code></pre>
<p>Notice that we’ve simulated 2 sets of <span class="math inline">\(Y\)</span> as 2 simulation replicates. Here we’ll focus on the first data-set.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw">dim</span>(dat<span class="op">$</span>data<span class="op">$</span>Y)</a></code></pre></div>
<pre><code>## [1] 574   2</code></pre>
<p>Here are the 3 “true” signals in the first data-set:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw">plot</span>(dat<span class="op">$</span>data<span class="op">$</span>true_coef[,<span class="dv">1</span>], <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">ylab=</span><span class="st">'effect size'</span>)</a></code></pre></div>
<p><img src="finemapping_files/figure-html/unnamed-chunk-4-1.png" width="700"></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">signal_index =<span class="st"> </span><span class="kw">which</span>(dat<span class="op">$</span>data<span class="op">$</span>true_coef[,<span class="dv">1</span>] <span class="op">!=</span><span class="st"> </span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="kw">print</span>(signal_index)</a></code></pre></div>
<pre><code>## [1] 403 653 773</code></pre>
<p>So the underlying causal variables are 403, 653 and 773.</p>
</div>
<div id="simple-regression-summary-statistics" class="section level2">
<h2 class="hasAnchor">
<a href="#simple-regression-summary-statistics" class="anchor"></a>Simple regression summary statistics</h2>
<p>The data-set additionally provides summary statistics for fitting univariate simple regression variable by variable. The results are <span class="math inline">\(\hat{\beta}\)</span> and <span class="math inline">\(SE(\hat{\beta})\)</span> from which z-scores can be derived. Again we focus only on results from the first data-set:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">z_scores =<span class="st"> </span>dat<span class="op">$</span>sumstats[<span class="dv">1</span>,,] <span class="op">/</span><span class="st"> </span>dat<span class="op">$</span>sumstats[<span class="dv">2</span>,,]</a>
<a class="sourceLine" id="cb10-2" data-line-number="2">z_scores =<span class="st"> </span>z_scores[,<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb10-3" data-line-number="3"><span class="kw">plot</span>(z_scores, <span class="dt">pch=</span><span class="dv">16</span>)</a>
<a class="sourceLine" id="cb10-4" data-line-number="4"><span class="kw">points</span>(signal_index, z_scores[signal_index], <span class="dt">col =</span> <span class="st">"red"</span>, <span class="dt">pch =</span> <span class="dv">16</span>)</a></code></pre></div>
<p><img src="finemapping_files/figure-html/unnamed-chunk-6-1.png" width="700"></p>
</div>
<div id="fine-mapping-with-susier" class="section level2">
<h2 class="hasAnchor">
<a href="#fine-mapping-with-susier" class="anchor"></a>Fine-mapping with <code>susieR</code>
</h2>
<p>For starters, we assume there are at most 5 causal variables, i.e., set <code>L=5</code>, although SuSiE is robust to the choice of <code>L</code>.</p>
<p>We set SuSiE prior variance to 0.1, and update residual variance in the variational algorithm that fits SuSiE model. The <code>susieR</code> function call is:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">fitted =<span class="st"> </span>susieR<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/susieR/topics/susie">susie</a></span>(dat<span class="op">$</span>data<span class="op">$</span>X, dat<span class="op">$</span>data<span class="op">$</span>Y[,<span class="dv">1</span>],</a>
<a class="sourceLine" id="cb11-2" data-line-number="2">                       <span class="dt">L=</span><span class="dv">5</span>,</a>
<a class="sourceLine" id="cb11-3" data-line-number="3">                       <span class="dt">estimate_residual_variance =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb11-4" data-line-number="4">                       <span class="dt">prior_variance =</span> <span class="fl">0.1</span>, </a>
<a class="sourceLine" id="cb11-5" data-line-number="5">                       <span class="dt">intercept=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-6" data-line-number="6">                       <span class="dt">tol=</span><span class="fl">1e-3</span>)</a></code></pre></div>
<div id="confidence-sets" class="section level3">
<h3 class="hasAnchor">
<a href="#confidence-sets" class="anchor"></a>Confidence sets</h3>
<p>We obtain 95% confidence set by:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">sets =<span class="st"> </span>susieR<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/susieR/topics/susie_get_CS">susie_get_CS</a></span>(fitted,</a>
<a class="sourceLine" id="cb12-2" data-line-number="2">                            <span class="dt">coverage =</span> <span class="fl">0.95</span>,</a>
<a class="sourceLine" id="cb12-3" data-line-number="3">                            <span class="dt">X=</span> dat<span class="op">$</span>data<span class="op">$</span>X, </a>
<a class="sourceLine" id="cb12-4" data-line-number="4">                            <span class="dt">min_abs_corr =</span> <span class="fl">0.1</span>)</a></code></pre></div>
<p>Notice that by passing to <code>susie_get_CS</code> function the data matrix <code>X</code>, we further filter the sets identified by removing those having absolute correlation between any pairs of variables in the set smaller than specified value, which is 0.1 in the function call above. We call this a “purity” filter.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">print</span>(sets)</a></code></pre></div>
<pre><code>## $cs
## $cs[[1]]
## [1] 773 777
## 
## $cs[[2]]
##  [1] 362 372 373 374 379 381 383 384 386 387 388 389 391 392 396 397 398
## [18] 399 400 401 403 404 405 407 408 415
## 
## $cs[[3]]
## [1] 653
## 
## 
## $purity
##   min.abs.corr mean.abs.corr median.abs.corr
## 1    0.9815726     0.9907863       0.9907863
## 2    0.8686309     0.9673674       0.9756251
## 3    1.0000000     1.0000000       1.0000000
## 
## $cs_index
## [1] 1 2 3</code></pre>
<p>The 3 causal signals have been captured by the 3 CS reported here. The 3rd CS contains many variables, including the true causal variable <code>403</code>. The minimum absolute correlation is 0.86.</p>
<p>If we use the default 90% coverage for confidence sets, we still capture the 3 signals, but “purity” of the 3rd CS is now 0.91 and size of the CS is also a bit smaller.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">sets =<span class="st"> </span>susieR<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/susieR/topics/susie_get_CS">susie_get_CS</a></span>(fitted,</a>
<a class="sourceLine" id="cb15-2" data-line-number="2">                            <span class="dt">X=</span> dat<span class="op">$</span>data<span class="op">$</span>X, </a>
<a class="sourceLine" id="cb15-3" data-line-number="3">                            <span class="dt">min_abs_corr =</span> <span class="fl">0.1</span>)</a></code></pre></div>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="kw">print</span>(sets)</a></code></pre></div>
<pre><code>## $cs
## $cs[[1]]
## [1] 773 777
## 
## $cs[[2]]
##  [1] 373 374 379 381 383 384 386 387 388 389 391 392 396 399 400 401 403
## [18] 404 405 407 408
## 
## $cs[[3]]
## [1] 653
## 
## 
## $purity
##   min.abs.corr mean.abs.corr median.abs.corr
## 1    0.9815726     0.9907863       0.9907863
## 2    0.9119572     0.9744588       0.9779763
## 3    1.0000000     1.0000000       1.0000000
## 
## $cs_index
## [1] 1 2 3</code></pre>
</div>
<div id="posterior-inclusion-probability" class="section level3">
<h3 class="hasAnchor">
<a href="#posterior-inclusion-probability" class="anchor"></a>Posterior inclusion probability</h3>
<p>Previously we’ve determined that summing over 3 single effect regression models is approperate for our application. Here we summarize the variable selection results by computing posterior inclusion probability for SuSiE model:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">pip =<span class="st"> </span>susieR<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/susieR/topics/susie_get_PIP">susie_get_PIP</a></span>(fitted, sets<span class="op">$</span>cs_index)</a></code></pre></div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">plot</span>(pip, <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">ylab=</span><span class="st">'PIP'</span>)</a>
<a class="sourceLine" id="cb19-2" data-line-number="2"><span class="kw">points</span>(signal_index, pip[signal_index], <span class="dt">col =</span> <span class="st">"red"</span>, <span class="dt">pch =</span> <span class="dv">16</span>)</a></code></pre></div>
<p><img src="finemapping_files/figure-html/unnamed-chunk-13-1.png" width="700"></p>
<p>The true causal variables are colored red. Of interest is the cluster around position 400. The true signal is 403 but apparently it does not have the highest PIP. To compare ranking of PIP and original z-score in that CS:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">z3 =<span class="st"> </span><span class="kw">cbind</span>(sets<span class="op">$</span>cs[[<span class="dv">3</span>]], z_scores[sets<span class="op">$</span>cs[[<span class="dv">3</span>]]], pip[sets<span class="op">$</span>cs[[<span class="dv">3</span>]]])</a>
<a class="sourceLine" id="cb20-2" data-line-number="2"><span class="kw">colnames</span>(z3) =<span class="st"> </span><span class="kw">c</span>(<span class="st">'position'</span>, <span class="st">'z-score'</span>, <span class="st">'PIP'</span>)</a>
<a class="sourceLine" id="cb20-3" data-line-number="3">z3[<span class="kw">order</span>(z3[,<span class="dv">2</span>], <span class="dt">decreasing =</span> <span class="ot">TRUE</span>),]</a></code></pre></div>
<pre><code>##    position     z-score         PIP 
## 653.0000000  -6.9366153   0.9998735</code></pre>
</div>
<div id="choice-of-priors" class="section level3">
<h3 class="hasAnchor">
<a href="#choice-of-priors" class="anchor"></a>Choice of priors</h3>
<p>We found that SuSiE is generally robust to choice of priors. Here we set prior variance to 0.2, and compare with previous results:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">fitted =<span class="st"> </span>susieR<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/susieR/topics/susie">susie</a></span>(dat<span class="op">$</span>data<span class="op">$</span>X, dat<span class="op">$</span>data<span class="op">$</span>Y[,<span class="dv">1</span>],</a>
<a class="sourceLine" id="cb22-2" data-line-number="2">                       <span class="dt">L=</span><span class="dv">5</span>,</a>
<a class="sourceLine" id="cb22-3" data-line-number="3">                       <span class="dt">estimate_residual_variance =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb22-4" data-line-number="4">                       <span class="dt">prior_variance =</span> <span class="fl">0.2</span>, </a>
<a class="sourceLine" id="cb22-5" data-line-number="5">                       <span class="dt">intercept=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb22-6" data-line-number="6">                       <span class="dt">tol=</span><span class="fl">1e-3</span>)</a>
<a class="sourceLine" id="cb22-7" data-line-number="7">sets =<span class="st"> </span>susieR<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/susieR/topics/susie_get_CS">susie_get_CS</a></span>(fitted,</a>
<a class="sourceLine" id="cb22-8" data-line-number="8">                            <span class="dt">X=</span> dat<span class="op">$</span>data<span class="op">$</span>X, </a>
<a class="sourceLine" id="cb22-9" data-line-number="9">                            <span class="dt">min_abs_corr =</span> <span class="fl">0.1</span>)</a>
<a class="sourceLine" id="cb22-10" data-line-number="10">pip =<span class="st"> </span>susieR<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/susieR/topics/susie_get_PIP">susie_get_PIP</a></span>(fitted, sets<span class="op">$</span>cs_index)</a>
<a class="sourceLine" id="cb22-11" data-line-number="11"><span class="kw">plot</span>(pip, <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">ylab=</span><span class="st">'PIP'</span>)</a>
<a class="sourceLine" id="cb22-12" data-line-number="12"><span class="kw">points</span>(signal_index, pip[signal_index], <span class="dt">col =</span> <span class="st">"red"</span>, <span class="dt">pch =</span> <span class="dv">16</span>)</a></code></pre></div>
<p><img src="finemapping_files/figure-html/unnamed-chunk-15-1.png" width="700"></p>
<p>which largely remains unchanged. It is also possible to use <code>estimate_prior_variance = TRUE</code> to estimate prior variance estimates in variational updates. (FIXME: need to comment on whether this is recommanded.)</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#the-data-set">The data-set</a></li>
      <li><a href="#simple-regression-summary-statistics">Simple regression summary statistics</a></li>
      <li><a href="#fine-mapping-with-susier">Fine-mapping with <code>susieR</code></a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Matthew Stephens, Yuxin Zou, Peter Carbonetto, Gao Wang.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
