# Generated by cpp11: do not edit by hand

random_order <- function(p, numiter) {
  .Call(`_susieRSlidePrior_random_order`, p, numiter)
}

caisa_cpp <- function(X, w, sa2, pi_init, beta_init, r_init, sigma2, o_r, maxiter, miniter, convtol, epstol, method_q, updatepi, updatesigma, verbose) {
  .Call(`_susieRSlidePrior_caisa_cpp`, X, w, sa2, pi_init, beta_init, r_init, sigma2, o_r, maxiter, miniter, convtol, epstol, method_q, updatepi, updatesigma, verbose)
}

mr_ash_rss_cpp <- function(bhat, shat, z, R, var_y, n, sigma2_e, s0, w0, mu1_init, tol, max_iter, update_w0, update_sigma, compute_ELBO, standardize) {
  .Call(`_susieRSlidePrior_mr_ash_rss_cpp`, bhat, shat, z, R, var_y, n, sigma2_e, s0, w0, mu1_init, tol, max_iter, update_w0, update_sigma, compute_ELBO, standardize)
}

slide_ser_native <- function(xx_, xh_, hh_, xy_, hy_, V_, sigma2_, fixed_) {
  .Call(`_susieRSlidePrior_slide_ser_native`, xx_, xh_, hh_, xy_, hy_, V_, sigma2_, fixed_)
}

slide_prior_ser_native <- function(xx_, xh_, hh_, xy_, hy_, V_, sigma2_, grid_, prior_, forced_) {
  .Call(`_susieRSlidePrior_slide_prior_ser_native`, xx_, xh_, hh_, xy_, hy_, V_, sigma2_, grid_, prior_, forced_)
}
